//(define fun (a b)
    //(print  (cdr (cons (cons a b) (cons b a)) ))
    //(number? a)
    //(print "World")
    //(cons a b)
    //(car b)
    //(car a)

//)

//(print (fun "yes" "no"))
(set a "A")
(print (list? a))
//(print "hello")
//(print (- 4 5))
//(set a "2")
//(print a)
//(set b (cons a a))
//(print b)
//(set c (cons a b))
//(print c)
//(print (cons c a))